web/web/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rooms', views.rooms, name='rooms'),
    path('staf', views.staf, name='staf'),
    path('booking/', views.booking, name='booking'),
    path('about/', views.about, name='about'),
    path('occupancy_of_rooms', views.occupancy_edit, name='occupancy_of_rooms'),
    path('profile/', views.profile, name='profile'),
    path('contacts/', views.contacts, name='contacts'),
    path('check_room_availability/<str:date_of_arrival>/<str:date_of_departure>/',
         views.check_room_availability, name='check_room_availability'),
    path('generate_report/', views.generate_report, name='generate_report'),
    path('generate_report_1/', views.generate_report_1, name='generate_report_1'),
    path('now_book/', views.how_book, name='how_book'),
]

web/web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/web/main/models.py
from django.db import models
from django.contrib.auth.models import User as DefaultUser

class Post(models.Model):
    name_post=models.CharField(max_length=32)
    def __str__(self):
        return self.name_post

class Status(models.Model):
    status=models.CharField(max_length=32)
    def __str__(self):
        return self.status

class Type_room(models.Model):
    type=models.CharField(max_length=16)

    def __str__(self):
        return self.type

class User(models.Model):
    user=models.OneToOneField(DefaultUser, on_delete=models.CASCADE)
    login=models.CharField(max_length=32,default='')
    password_user=models.CharField(max_length=256,default='')
    name=models.CharField(max_length=16,default='')
    surname=models.CharField(max_length=32,default='')
    patronymic=models.CharField(max_length=20,default='')
    email=models.CharField(max_length=256,default='')
    phone_number=models.CharField(max_length=17,default='')
    def __str__(self):
        return self.login

class Staffer(models.Model):
    user = models.OneToOneField(DefaultUser, on_delete=models.CASCADE)
    login = models.CharField(max_length=32)
    password_user = models.CharField(max_length=32)
    name = models.CharField(max_length=16)
    surname = models.CharField(max_length=32)
    patronymic = models.CharField(max_length=20)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    def __str__(self):
        return self.login

class Request(models.Model):
    main_place=models.IntegerField()
    additional_place=models.IntegerField()
    date_of_arrival=models.DateField()
    date_of_departure=models.DateField()
    status=models.ForeignKey('Status', on_delete=models.CASCADE)
    user = models.ForeignKey('User', on_delete=models.CASCADE)


class Request_Staffer(models.Model):
    request=models.ForeignKey('Request', on_delete=models.CASCADE)
    staffer=models.ForeignKey('Staffer', on_delete=models.CASCADE)

class Room(models.Model):
    description=models.TextField(blank=True)
    name_room=models.CharField(max_length=64)
    type_room = models.ForeignKey('Type_room', on_delete=models.CASCADE)
    def __str__(self):
        return f'Комната: {self.name_room} | Тип: {self.type_room.type}'

    def is_available(self, date_of_arrival, date_of_departure):
        # Проверяем, есть ли бронирования для номера в указанный период
        bookings = occupancy_of_rooms.objects.filter(
            room=self,
            date_of_arrival__lte=date_of_departure,
            date_of_departure__gte=date_of_arrival,
        )
        return not bookings.exists()

class occupancy_of_rooms(models.Model):
    date_of_arrival = models.DateField()
    date_of_departure = models.DateField()
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.room} | Даты занятости номера: {self.date_of_arrival} - {self.date_of_departure}'

class Room_request(models.Model):
    request = models.ForeignKey('Request', on_delete=models.CASCADE)
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        super(Room_request, self).save(*args, **kwargs)

class Room_price(models.Model):
    room = models.ForeignKey('Room', on_delete=models.CASCADE, related_name='prices')
    additional_place = models.BooleanField()
    price = models.DecimalField(max_digits=8,decimal_places=2)

web/web/main/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import Request, Room
from bootstrap_datepicker_plus.widgets import DatePickerInput
from .models import occupancy_of_rooms

class RequestForm(ModelForm):
    room = forms.ModelChoiceField(label='',queryset=Room.objects.all(), widget=forms.Select(attrs={
        'class': 'form-control',
        'placeholder': 'Выберите комнату'
    }), empty_label=None)

    main_place = forms.IntegerField(label='', min_value=1, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Количество гостей'
    }))

    additional_place = forms.IntegerField(label='', min_value = 0, widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'Количество дополнительных мест'
    }))

    date_of_arrival = forms.DateField(label='', widget=DatePickerInput(format='%d/%m/%Y', attrs={
        'placeholder': 'Выберите дату заезда',
         'class': 'form-control datepicker'
    }))

    date_of_departure = forms.DateField(label='', widget=DatePickerInput(format='%d/%m/%Y', attrs={
        'placeholder': 'Выберите дату выезда',
        'class': 'form-control datepicker'
    }))

    def clean_main_place(self):
        main_place = self.cleaned_data['main_place']
        if main_place < 1:
            raise ValidationError("Количество гостей должно быть не менее 1")
        return main_place

    def clean_additional_place(self):
        additional_place = self.cleaned_data['additional_place']
        if additional_place < 0:
            raise ValidationError("Количество дополнительных мест не может быть отрицательным")
        return additional_place

    class Meta:
        model = Request
        fields = ['room', 'main_place', 'additional_place', 'date_of_arrival', 'date_of_departure']


class RoomAvailabilityForm(forms.Form):
    room_number = forms.IntegerField(label='Номер комнаты')
    date_of_arrival = forms.DateField(label='Дата заезда')
    date_of_departure = forms.DateField(label='Дата выезда')

web/web/main/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import RequestForm
from .models import Room, Request, Status, Room_request, occupancy_of_rooms, User, Request_Staffer
from django.contrib import messages
from django.shortcuts import render, redirect
from django.shortcuts import render
from .forms import RoomAvailabilityForm
from datetime import datetime
from reportlab.lib.pagesizes import letter, landscape
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from django.shortcuts import get_object_or_404

def index(request):
    return render(request, 'main/index.html')

def how_book(request):
    return render(request, 'main/How_book.html')

def rooms(request):
    rooms = Room.objects.all()
    arrival_date = request.GET.get('arrival_date')
    departure_date = request.GET.get('departure_date')

    if arrival_date and departure_date:
        # Пользователь указал даты заезда и выезда
        occupied_rooms = occupancy_of_rooms.objects.filter(
            date_of_arrival__lte=datetime.strptime(departure_date, '%Y-%m-%d'),
            date_of_departure__gte=datetime.strptime(arrival_date, '%Y-%m-%d')
        )
        rooms = rooms.exclude(id__in=occupied_rooms.values_list('room_id', flat=True))

    return render(request, 'main/rooms.html', {'rooms': rooms})

def about(request):
    return render(request, 'main/about.html')

def profile(request):
    return render(request, 'main/profile.html')

def contacts(request):
    return render(request, 'main/contacts.html')

def check_room_availability(request):
    return render(request, 'main/check_room_availability.html')

@login_required
def booking(request, room_id=None):
    errors = []
    user_login = request.user.user.id
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            date_of_arrival = form.cleaned_data['date_of_arrival']
            date_of_departure = form.cleaned_data['date_of_departure']

            if date_of_arrival >= date_of_departure:
                errors.append('Дата заезда должна быть раньше даты выезда')
            else:
                booking_req = form.save(commit=False)
                booking_req.user_id = user_login
                booking_req.status_id = 1
                booking_req.save()
                room_id = request.POST.get('room')
                room = get_object_or_404(Room, id=room_id)
                form.initial['room'] = room
                room = form.cleaned_data['room']
                r = Room_request(request=booking_req, room=room)
                r.save()
                messages.success(request, 'Заявка успешно отправлена')
                return redirect('index')
        else:
            errors.append('Ошибка в заполнении формы')
    else:
        if room_id:
            room = get_object_or_404(Room, id=room_id)
            initial_data = {'room': room}
            form = RequestForm(initial=initial_data)
        else:
            form = RequestForm()

    context = {'form': form, 'errors': errors}
    return render(request, 'main/booking.html', context)

def staf(request):
    statuses = Status.objects.all()
    req = Request.objects.order_by('status__id')
    rooms = Room.objects.all()

    if request.method == 'POST':
        for el in req:
            status = request.POST.get(str(el.id))

            # Проверяем должность сотрудника
            if request.user.staffer.post_id != 2:
                if status:
                    el.status_id = status
                    el.save()
                    # Создаем запись в модели Request_Staffer
                    Request_Staffer.objects.create(request=el, staffer=request.user.staffer)

        # Обновляем список заявок после сохранения изменений в базу данных
        req = Request.objects.all()

    context = {
        'statuses': statuses,
        'req': req,
        'rooms': rooms
    }

    return render(request, 'main/staf.html', context)


def occupancy_edit(request):
    rooms = Room.objects.all()
    if request.method == 'POST':
        date_of_arrival = request.POST.get('date_of_arrival')
        date_of_departure = request.POST.get('date_of_departure')
        room_id = request.POST.get('room_id')

        # получаем список объектов occupancy_of_rooms для данной комнаты
        occupancies = occupancy_of_rooms.objects.filter(room_id=room_id)

        #если объекта нет, создаем новый
        room = Room.objects.get(id=room_id)
        occupancy = occupancy_of_rooms(room_id=room_id, date_of_arrival=date_of_arrival, date_of_departure=date_of_departure)
        occupancy.save()

        occupancy.date_of_arrival = date_of_arrival
        occupancy.date_of_departure = date_of_departure
        occupancy.save()

    return render(request, 'main/occupancy_of_rooms.html', {'rooms': rooms})


def profile(request):
    user = request.user.user
    user_requests = Request.objects.filter(user=user)
    room_requests = Room_request.objects.filter(request__in=user_requests)
    requests_data = []
    for room_request in room_requests:
        request_data = {
            'date_of_arrival': room_request.request.date_of_arrival,
            'date_of_departure': room_request.request.date_of_departure,
            'main_place': room_request.request.main_place,
            'additional_place': room_request.request.additional_place,
            'status': room_request.request.status,
            'room_number': room_request.room
        }
        requests_data.append(request_data)
    return render(request, 'main/profile.html', {'requests_data': requests_data})

def check_room_availability(request, date_of_arrival=None, date_of_departure=None):
    if request.method == 'POST':
        form = RoomAvailabilityForm(request.POST)
        if form.is_valid():
            room_number = form.cleaned_data['room_number']
            date_of_arrival = form.cleaned_data['date_of_arrival']
            date_of_departure = form.cleaned_data['date_of_departure']
        else:
            room_number = request.POST.get('room_number')
            date_of_arrival = request.POST.get('date_of_arrival')
            date_of_departure = request.POST.get('date_of_departure')
    else:
        form = RoomAvailabilityForm()
        if date_of_arrival and date_of_departure:
            # Устанавливаем значения дат в форме, если они переданы в GET-запросе
            form.fields['date_of_arrival'].initial = datetime.strptime(date_of_arrival, '%Y-%m-%d').date()
            form.fields['date_of_departure'].initial = datetime.strptime(date_of_departure, '%Y-%m-%d').date()
        room_number = request.GET.get('room_number')
        date_of_arrival = request.GET.get('date_of_arrival')
        date_of_departure = request.GET.get('date_of_departure')
    message = None
    if room_number and date_of_arrival and date_of_departure:
        # Проверка занятости комнаты
        try:
            room = Room.objects.get(id=room_number)
        except Room.DoesNotExist:
            message = 'Комната с номером {} не найдена'.format(room_number)
        else:
            occupancy = occupancy_of_rooms.objects.filter(
                room=room,
                date_of_arrival__lte=date_of_departure,
                date_of_departure__gte=date_of_arrival,
            ).first()
            if occupancy:
                message = 'Комната занята в указанные даты'
            else:
                message = 'Комната свободна в указанные даты'
    context = {
        'form': form,
        'message': message,
    }
    return render(request, 'main/check_room_availability.html', context)


def generate_report(response):
    # Получаем данные из базы данных
    rooms = Room.objects.all()
    # Создаем PDF-документ
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="example.pdf"'
    pdfmetrics.registerFont(TTFont('Roboto', 'C:/Users/yulia/Downloads/Roboto-Italic.ttf'))
    # Создаем canvas объект и настраиваем его
    p = canvas.Canvas(response, pagesize=landscape(letter))
    p.setTitle("Отчет по занятости номеров")

    # Устанавливаем шрифт и кодировку
    p.setFont("Roboto", 16)
    # Добавляем заголовок отчета
    p.drawCentredString(400, 720, "Отчет по занятости номеров")

    # Добавляем информацию о заказах
    y = 500
    for room in rooms:
        p.setFont("Roboto", 14)
        p.drawString(100, y, f"Номер комнаты {room.id}")
        occupancies = occupancy_of_rooms.objects.filter(room=room)
        y -= 30
        p.setFont("Roboto", 12)
        p.drawString(100, y, f"Дата заезда")
        p.drawString(200, y, f"Дата выезда")
        p.line(100, y - 3, 700, y - 3)
        y -= 20
        for occup in occupancies:
            if y < 100:
                p.showPage()
                y = 650
                p.setFont("Roboto", 16)
                p.drawCentredString(400, 720, "Отчет по занятости номеров")
                p.setFont("Roboto", 12)
                p.drawString(100, y, f"Номер комнаты {room.id}")
                y -= 30
                p.drawString(100, y, f"Дата заезда")
                p.drawString(200, y, f"Дата выезда")
                p.line(100, y - 3, 700, y - 3)
                y -= 20
            p.setFont("Roboto", 10)
            p.drawString(100, y, f"{occup.date_of_arrival}")
            p.drawString(200, y, f"{occup.date_of_departure}")
            y -= 20
        y -= 30
    # Сохраняем PDF-документ и возвращаем его
    p.showPage()
    p.save()
    return response


def generate_report_1(request):
    # Получаем данные из базы данных и сортируем по возрастанию номера заявки
    requests = Request.objects.order_by('id').all()

    # Остальной код отчета остается без изменений
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="example.pdf"'

web/web/main/templates/main/How_book.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel ="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/4d30ec1328.js" crossorigin="anonymous"></script>
    <title>Гостиница</title>
</head>
<body>
<div class='header'>

    <div class="content flex_space">
        <div class="logo">
            <img src="https://sun9-69.userapi.com/impg/0A1DNnptDkjnYO92vsaxYyqhg9r3uHt8_-Aw0Q/6o9i8uS4z_8.jpg?size=200x79&quality=95&sign=f32bbd4591cd9facc9791cfb339d8ee2&type=album" alt="">
        </div>
        <div class="navlinks">
            <ul id="menulist">
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'rooms' %}">Номера</a></li>
                <li><a href="{% url 'about' %}">О нас</a></li>
                <li><a href="{% url 'contacts' %}">Контакты</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'profile' %}"><button class="primary-btn">ЗАЯВКИ НА БРОНИРОВАНИЕ</button></a></li>
                {% endif %}
                {%if request.user.is_authenticated %}
                    <span>{{ request.user.username | title }}</span>
                   <li> <a href="{% url 'logout' %}">Выход</a></li>
                {%else%}
                    <li><a href="{% url 'login' %}">Войти</a></li>
                    <li><a href="{% url 'register' %}">Регистрация</a></li>
                {%endif%}
            </ul>

        </div>
    </div>

</div>

<main>
    <div class = "text" style="font-size: 1.6em; background-color: rgba(256, 256, 256, 0.5); border-radius: 10px; margin-top: 70px;padding: 20px ;">
Для начала процесса бронирования номера в подсистеме необходимо перейти на главную страницу и найти раздел «Войти».
В этом разделе необходимо ввести учетные данные, такие как логин и пароль. <br>
После ввода данных нажать на кнопку «Войти» для выполнения входа в подсистему.<br>
После успешного входа в систему, пользователь будет перенаправлен на главную страницу, где следует найти раздел «Номера».
В этом разделе предоставляется возможность указать дату заезда и дату выезда, чтобы найти свободные номера в заданный период.
После нажатия на кнопку «Найти свободные номера», подсистема выполнит поиск доступных номеров, соответствующих заданным критериям.<br>
Пользователь получает список номеров, которые свободны на выбранные даты.<br>
        Из предложенного списка номеров необходимо выбрать подходящий и нажать на кнопку «Забронировать».<br>
После этого откроется форма бронирования номера, где нужно заполнить обязательные поля, такие как даты заезда и выезда, количество основных и дополнительных мест.<br>
        Рекомендуется проверить правильность введенных данных и нажать на кнопку "Создать". После выполнения всех указанных действий, система создаст заявку на бронирование номера.<br>
Далее пользователь может отследить изменение статуса заявки, перейдя в раздел «Заявки на бронирование».
Там находится информация о всех заявках, которые пользователь отправил и есть возможность отслеживать статусы заявок.<br>
Следуя этим указаниям, пользователь сможет успешно бронировать номера в подсистеме.
</div>
</main>
</body>
</html>

web/web/main/templates/main/booking.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel ="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/4d30ec1328.js" crossorigin="anonymous"></script>
    <title>Бронирование номера</title>
</head>
<body>
<div class='header'>

    <div class="content flex_space">
        <div class="logo">
            <img src="https://sun9-69.userapi.com/impg/0A1DNnptDkjnYO92vsaxYyqhg9r3uHt8_-Aw0Q/6o9i8uS4z_8.jpg?size=200x79&quality=95&sign=f32bbd4591cd9facc9791cfb339d8ee2&type=album" alt="">
        </div>
        <div class="navlinks">
            <ul id="menulist">
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="{% url 'rooms' %}">Номера</a></li>
                <li><a href="#about">О нас</a></li>
                <li><a href="#contact">Контакты</a></li>
                <li><a href="{% url 'booking' %}"><button class="primary-btn">ЗАБРОНИРОВАТЬ НОМЕР</button></a></li>
                {%if request.user.is_authenticated %}
                    <span>{{ request.user.username | title }}</span>
                   <li> <a href="{% url 'logout' %}">Выход</a></li>
                {%else%}
                    <li><a href="{% url 'login' %}">Вход</a></li>
                    <li><a href="{% url 'register' %}">Регистрация</a></li>
                {%endif%}
            </ul>

        </div>
    </div>

</div>

<main>


{% block content %}

<form method="POST" style="text-align: center; margin: 60px 270px 0px 250px;background-color: rgba(256, 256, 256, 0.5);border-radius: 10px; padding:20px">
    <h1 style="text-align:center;margin:10px;">Заявка на бронирование</h1>
    {% csrf_token %}
    <div class="form-group" style="margin:50px 150px 20px 150px;">
        <label  for="{{ form.room.id_for_label }}"></label>
        {{ form.room }}
    </div>
    <div class="form-group" style="margin:0px 150px 20px 150px;">
        <label for="{{ form.main_place.id_for_label }}"></label>
        {{ form.main_place }}
    </div>
    <div class="form-group" style="margin:0px 150px 20px 150px;">
        <label for="{{ form.additional_place.id_for_label }}"></label>
        {{ form.additional_place }}
    </div>
    <div class="form-group" style="margin:0px 150px 20px 150px;">
        <label for="{{ form.date_of_arrival.id_for_label }}"></label>
        {{ form.date_of_arrival }}
    </div>
    <div class="form-group" style="margin:0px 150px 60px 150px;">
        <label for="{{ form.date_of_departure.id_for_label }}"></label>
        {{ form.date_of_departure }}
    </div>
     {{ form.media }}
    <button type="submit" class="btn btn-primary" style="padding:10px 20px; background-color:rgba(222, 184, 135, 0.9); border:none;">Создать</button>
</form>
{% endblock content %}
</main>
</body>
</html>

web/web/main/templates/main/staf.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel ="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/4d30ec1328.js" crossorigin="anonymous"></script>
    <title>Гостиница</title>
</head>
<body>
<div class='header'>

    <div class="content flex_space">
        <div class="logo">
            <img src="https://sun9-69.userapi.com/impg/0A1DNnptDkjnYO92vsaxYyqhg9r3uHt8_-Aw0Q/6o9i8uS4z_8.jpg?size=200x79&quality=95&sign=f32bbd4591cd9facc9791cfb339d8ee2&type=album" alt="">
        </div>
        <div class="navlinks">
            <ul id="menulist">
                <li><a href="{% url 'occupancy_of_rooms' %}">Изменить занятость</a></li>
                {%if request.user.is_authenticated %}
                    <span>{{ request.user.username | title }}</span>
                   <li> <a href="{% url 'logout' %}">Выход</a></li>
                {%else%}
                    <li><a href="{% url 'login' %}">Вход</a></li>
                {%endif%}

            </ul>
        </div>
    </div>

</div>

<main>
        <div class="messages">
            {% if messages %}

			{% for message in messages %}
				<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
					{{ message }}
				</div>
			{% endfor %}

		{% endif %}
        </div>
</main>
<a href="{% url 'generate_report_1' %}"><button style="margin-left:670px; margin-top: 10px; margin-bottom: 10px; padding: 20px; border-radius: 10px;" class="primary-btn">Скачать отчет <i class="fa-solid fa-download"></i></i></button></a>
    {% for el in req %}
    <div class="box-1">
        <h2>Заявка № {{ el.id }}</h2>
        <p> Дата заезда: {{ el.date_of_arrival }}<br>
        Дата выезда: {{ el.date_of_departure }} <br>
        {% for room_request in el.room_request_set.all %}
            Комната: {{ room_request.room.id }} {{ room_request.room.name_room }} <br> Тип: {{ room_request.room.type_room.type }}<br>
        Количество основных мест: {{el.main_place}} <br>
        Количество дополнительных мест: {{ el.additional_place}}</p>

        {% endfor %}
        <p>Имя: {{ el.user.name }}<br>
        Фамилия: {{ el.user.surname }}<br>
        Отчество: {{ el.user.patronymic }}<br>
        Email: {{ el.user.email }}<br>
        Телефон: {{ el.user.phone_number }}</p>
        <form method="post">
            {% csrf_token %}
            <select name="{{ el.id }}">
                {% for status in statuses %}
                    {% if status == el.status %}
                        <option value="{{ status.id }}" selected>{{ status.status }}</option>
                    {% else %}
                        <option value="{{ status.id }}">{{ status.status }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <button type="submit">Сохранить</button>
            <div class="request">
                <a href="{% url 'check_room_availability' el.date_of_arrival el.date_of_departure %}" class="btn btn-primary">Проверить занятость</a>
            </div>

        </form>
    </div>
{% endfor %}

</body>


</html>